// Copyright 2025 MyCompany
package com.thecompany.consultme.buildlogic

/**
 * Renders a [ModuleGraph] as a Mermaid `graph` block embedded in a Markdown
 * fence. GitHub renders Mermaid code blocks inline.
 *
 * Output shape:
 *
 * ```mermaid
 * graph TD
 *   :app --> :core-ui
 *   :app --> :feature-example
 *   ...
 * ```
 */
class MermaidModuleGraphRenderer(
    private val direction: GraphDirection = GraphDirection.TopDown,
) : ModuleGraphRenderer {
    override fun render(graph: ModuleGraph): String = buildString {
        appendLine("# Module dependency graph")
        appendLine()
        appendLine("Generated by `./gradlew moduleGraph`. Do not edit by hand.")
        appendLine()
        appendLine("```mermaid")
        appendLine("graph ${direction.token}")
        // Stable ordering keeps the committed file deterministic across runs.
        graph.edges
            .sortedWith(compareBy({ it.from.path }, { it.to.path }))
            .forEach { edge ->
                appendLine("  ${edge.from.path} --> ${edge.to.path}")
            }
        graph.nodes
            .filter { node -> graph.edges.none { it.from == node || it.to == node } }
            .sortedBy { it.path }
            .forEach { node ->
                appendLine("  ${node.path}")
            }
        appendLine("```")
    }

    enum class GraphDirection(val token: String) {
        TopDown("TD"),
        LeftRight("LR"),
    }
}
